global using System;
global using System.Collections.Immutable;
global using System.Linq;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.UI.Xaml;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using TimePunch_WinUI_Uno_StackedUI_Demo.Models;
global using TimePunch_WinUI_Uno_StackedUI_Demo.Services.Endpoints;
global using Uno.Extensions.Http.Kiota;
global using Windows.ApplicationModel.Activation;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
